eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8099  #default port where the service will be started

spring:
  application:
    name: demomicroservice



